knpu_oauth2_client:
    clients:
        google:
            type: generic
            provider_class: League\OAuth2\Client\Provider\Google
            client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
            redirect_route: '%env(resolve:GOOGLE_REDIRECT_URI)%'
            redirect_params: {}
            provider_options:
                urlAuthorize: 'https://accounts.google.com/o/oauth2/v2/auth'
                urlAccessToken: 'https://oauth2.googleapis.com/token'
                urlResourceOwnerDetails: 'https://www.googleapis.com/oauth2/v3/userinfo'