# config/packages/knpu_oauth2_client.yaml
knpu_oauth2_client:
    clients:
        twitter:
            type: generic
            provider_class: App\Service\OAuth\TwitterProvider
            client_id: '%env(resolve:TWITTER_CLIENT_ID)%'
            client_secret: '%env(resolve:TWITTER_CLIENT_SECRET)%'
            redirect_route: oauth_twitter_exchange_token
            redirect_params: {}
            provider_options:
                urlAuthorize: 'https://twitter.com/i/oauth2/authorize'
                urlAccessToken: 'https://api.twitter.com/2/oauth2/token'
                urlResourceOwnerDetails: 'https://api.twitter.com/2/users/me'
                scopes: 'tweet.read users.read offline.access'
                scopeSeparator: ' '
        
        google:
            type: generic
            provider_class: League\OAuth2\Client\Provider\Google
            client_id: '%env(resolve:GOOGLE_CLIENT_ID)%'
            client_secret: '%env(resolve:GOOGLE_CLIENT_SECRET)%'
            redirect_route: '%env(resolve:GOOGLE_REDIRECT_URI)%'
            redirect_params: {}
            provider_options:
                urlAuthorize: 'https://accounts.google.com/o/oauth2/v2/auth'
                urlAccessToken: 'https://oauth2.googleapis.com/token'
                urlResourceOwnerDetails: 'https://www.googleapis.com/oauth2/v3/userinfo'