framework:
    messenger:
        buses:
            command.bus:
                middleware:
                    - App\Messenger\Middleware\BusinessExceptionMiddleware
        transports:
            async-high:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-high:
                            binding_keys: [async-high]
                retry_strategy:
                    max_retries: 0
            async-medium:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-medium:
                            binding_keys: [async-medium]
                retry_strategy:
                    max_retries: 0
            async-low:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                options:
                    exchange:
                        name: messages
                        type: direct
                    auto_setup: true
                    queues:
                        async-low:
                            binding_keys: [async-low]
                retry_strategy:
                    max_retries: 0
            sync: "sync://"

        routing:
            'App\Application\Command\CreateStreamCommand': sync
            'App\Application\Command\CreateStreamByUrlCommand': sync

            'App\Application\Command\UploadVideoCommand': sync
            'App\Application\Command\UploadVideoByUrlCommand': async-high

            'App\Application\Command\ExtractSoundCommand': async-high
            'App\Application\Command\ExtractSoundSuccessCommand': async-high

            'App\Application\Command\GenerateSubtitlesCommand': async-high
            'App\Application\Command\GenerateSubtitlesSuccessCommand': async-high

            'App\Application\Command\TransformSubtitleCommand': async-high
            'App\Application\Command\TransformSubtitleSuccessCommand': async-high

            'App\Application\Command\TransformVideoCommand': async-high
            'App\Application\Command\TransformVideoSuccessCommand': async-high
